run:
  #modules-download-mode: readonly
issues:
  exclude:
    - "break_"
    - "undbg"
    - "flags"
  exclude-rules:
    - path: benchmarks_data
      linters:
        - stylecheck
        - lll
    - path: "(.*)_test\\.go"
      linters:
        - goconst
    - path: low.go
      linters:
        - deadcode
        - unused
    - path: "unmarshal\\.go"
      linters:
        - dupl
    - source: protected by mu
      linters:
        - godot
    - source: "var \\("
      linters:
        - gofumpt
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 30
  cyclop:
    max-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/stretchr/testify
          - nikand.dev/go/json2
          - nikand.dev/go/skip
          - tlog.app/go/errors
          - tlog.app/go/loc
          - tlog.app/go/tlog
  misspell:
  lll:
    line-length: 170
  goimports:
    local-prefixes: nikand.dev/go/json2
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - appendAssign
      - builtinShadow
      - commentedOutCode
      - octalLiteral
      - unnamedResult
      - whyNoLint
      - yodaStyleExpr

linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - golint
    - gomnd
    - ifshort
    - ireturn
    - mnd
    - nakedret
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - prealloc
    - recvcheck
    - testifylint
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - whitespace
    - wsl

    - wrapcheck # for now
