language: go

go:
  - "1.21"
  - "1.20"

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - i386
  - arm64

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
