language: go

env:
  - GO111MODULE=on

go:
  - "1.13"
  - "1.14"
  - "1.15"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
