// Code generated by "stringer -type Type ."; DO NOT EDIT.

package json

import "strconv"

const (
	_Type_name_0 = "None"
	_Type_name_1 = "Number"
	_Type_name_2 = "Array"
	_Type_name_3 = "Bool"
	_Type_name_4 = "Null"
	_Type_name_5 = "String"
	_Type_name_6 = "Object"
)

var (
	_Type_index_0 = [...]uint8{0, 4}
	_Type_index_1 = [...]uint8{0, 6}
	_Type_index_2 = [...]uint8{0, 5}
	_Type_index_3 = [...]uint8{0, 4}
	_Type_index_4 = [...]uint8{0, 4}
	_Type_index_5 = [...]uint8{0, 6}
	_Type_index_6 = [...]uint8{0, 6}
)

func (i Type) String() string {
	switch {
	case i == 0:
		return _Type_name_0
	case i == 78:
		return _Type_name_1
	case i == 91:
		return _Type_name_2
	case i == 98:
		return _Type_name_3
	case i == 110:
		return _Type_name_4
	case i == 115:
		return _Type_name_5
	case i == 123:
		return _Type_name_6
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
