// Code generated by "stringer -type=Type ."; DO NOT EDIT.

package json

import "strconv"

const (
	_Type_name_0 = "None"
	_Type_name_1 = "Number"
	_Type_name_2 = "ArrayStart"
	_Type_name_3 = "ArrayEnd"
	_Type_name_4 = "Bool"
	_Type_name_5 = "ObjKey"
	_Type_name_6 = "Null"
	_Type_name_7 = "String"
	_Type_name_8 = "ObjStart"
	_Type_name_9 = "ObjEnd"
)

var (
	_Type_index_0 = [...]uint8{0, 4}
	_Type_index_1 = [...]uint8{0, 6}
	_Type_index_2 = [...]uint8{0, 10}
	_Type_index_3 = [...]uint8{0, 8}
	_Type_index_4 = [...]uint8{0, 4}
	_Type_index_5 = [...]uint8{0, 6}
	_Type_index_6 = [...]uint8{0, 4}
	_Type_index_7 = [...]uint8{0, 6}
	_Type_index_8 = [...]uint8{0, 8}
	_Type_index_9 = [...]uint8{0, 6}
)

func (i Type) String() string {
	switch {
	case i == 0:
		return _Type_name_0
	case i == 78:
		return _Type_name_1
	case i == 91:
		return _Type_name_2
	case i == 93:
		return _Type_name_3
	case i == 98:
		return _Type_name_4
	case i == 107:
		return _Type_name_5
	case i == 110:
		return _Type_name_6
	case i == 115:
		return _Type_name_7
	case i == 123:
		return _Type_name_8
	case i == 125:
		return _Type_name_9
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
