version: 2
jobs:
  go1.14: &base
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/wd
    steps:
      - run: go version

      - checkout

      - run: go test -race -v ./...

  go1.13:
    <<: *base
    docker:
      - image: circleci/golang:1.13

  go1.12:
    <<: *base
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE=on

workflows:
  version: 2
  build:
    jobs:
      - go1.12
      - go1.13
      - go1.14
